version: '3.1'
services:
  app:
    image: node:18.13.0-alpine
    user: node
    working_dir: /app
    env_file:
      - .env
    environment:
      MYSQL_PORT: 3306
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mysql_dev
      - kafka
    networks:
      - net-dev
  mysql_dev:
    container_name: 'database'
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - '${MYSQL_PORT}:3306'
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    networks:
      - net-dev

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.3.0'
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      TZ: America/Sao_Paulo
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - net-dev

  kafka:
    image: 'confluentinc/cp-enterprise-kafka:7.3.0'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      TZ: America/Sao_Paulo
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      CONFLUENT_METRICS_ENABLE: 'false'

    networks:
      - net-dev

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '9021:9021'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - net-dev

volumes:
  database:

networks:
  net-dev:
    driver: bridge
